[package]
name = "elfware"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.2", features = ["mp3", "wav"] }
avian2d = "0.4"
bevy_aseprite_ultra = "0.7.0"
bevy_input = "0.17.3"
strum = "0.27.2"
strum_macros = "0.27.2"
